name: dexterstt
description: A speech to text app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  bloc: ^8.1.0
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  get_it: ^7.2.0
  go_router: ^12.1.1
  hive_flutter: ^1.1.0
  injectable: ^2.1.2
  intl: ^0.18.1
  json_annotation: ^4.7.0
  permission_handler: ^11.1.0
  pretty_dio_logger: ^1.3.1
  record: ^5.0.1
  shimmer: ^3.0.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  injectable_generator: ^2.1.6
  json_serializable: ^6.5.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/svg/
    - assets/images/

  fonts:
    - family: Wigrum
      fonts:
        - asset: assets/fonts/wigrum_medium.otf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
